version: "3.9"
services:
  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    env_file:
      - .env.postgres
  server:
    build: ..
    ports:
      - 8080:8080
    environment:
      FAKE_DATABASE_URL: postgresql://postgres:5432/kotlin_fake_api?user=user&password=password
      DATA_DIR: /data
      DB_DRIVER: org.postgresql.Driver
    depends_on:
      - postgres
